[package]
name = "cat-is-not-helper"
version = "1.0.0"
description = "Котик, который тапает вместе с тобой"
authors = ["Fgeeha"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "cat_is_not_helper_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-autostart = "2"
tauri-plugin-drag = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rdev = "0.5"
xcap = "0.9"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
base64 = "0.22"
chrono = "0.4"
dirs = "6"
trash = "5"
parking_lot = "0.12"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
